### PR TITLE
Fixes 'cache' directive in mailers not working in Rails 4.2

### LINKED ISSUE #3: Error: undefined method `view_cache_dependencies' in Rails 4.2.7
Using mailer_fragment_caching 0.0.4 + Rails 4.2.7, I get the following error when trying to send mail with a cached fragment:

     Failure/Error: MyMailer.send_something(...).deliver_now
     ActionView::Template::Error:
       undefined local variable or method `view_cache_dependencies' for #<#<Class:0x007fa149a70548>:0x007fa14ade13e8>

The problem seems to be that `ActionView::Helpers::CacheHelper#fragment_name_with_digest` calls `view_cache_dependencies`, which isn't defined.

For controllers, that method comes from ActionPack's `ActionController::Caching`, but mailers don't have it.

Any advice on how to get this working in Rails4? :)

### PR DESCRIPTION
**Pull request by gmcnaughton**
Closes #3.  Allows both Rails 3 and Rails 4 to use the `<% cache ... do %>` direction in mailer view templates.

Note: tested in Rails 3.2.22.2 and Rails 4.2.7, however I didn't test any earlier versions of Rails4

### CODE REVIEW

**Comment by gmcnaughton** [comment]
Verified that this patch works for Rails 4.0 and Rails 4.1!  (without it, they fail with the same error that 4.2 does)

**Comment by gilest** [comment]
Hey, thanks for putting this together! 😃 

Manually testing this against all of these Rails versions must be painful.

Since I'm on holiday at the moment and I have a bit of free time...

I've added few tests and set them up to run against different Rails versions using the appraisal gem. I shouldn't have really released the gem without a test suite anyway. 😅

**Comment by gmcnaughton** [comment]
Thanks @gilest! You = awesome

Now stop working on your holiday!
